steps:
  # Build and deploy backend
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'builds'
      - 'submit'
      - '--config=.cloudbuild/backend.yaml'
      - '--region=${_REGION}'
      - '--substitutions=_REGION=${_REGION},_REPOSITORY=${_REPOSITORY}'
      - '.'
    id: 'deploy-backend'

  # Build and deploy frontend-static (Configuration ①: Static file serving only)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'builds'
      - 'submit'
      - '--config=.cloudbuild/frontend-static.yaml'
      - '--region=${_REGION}'
      - '--substitutions=_REGION=${_REGION},_REPOSITORY=${_REPOSITORY}'
      - '.'
    id: 'deploy-frontend-static'
    waitFor: ['deploy-backend']

  # Build and deploy frontend (Configuration ②: Reverse proxy)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'builds'
      - 'submit'
      - '--config=.cloudbuild/frontend.yaml'
      - '--region=${_REGION}'
      - '--substitutions=_REGION=${_REGION},_REPOSITORY=${_REPOSITORY}'
      - '.'
    id: 'deploy-frontend'
    waitFor: ['deploy-backend']

  # Display URLs
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "================================================"
        echo "Deployment completed!"
        echo "================================================"
        echo "Backend URL:"
        gcloud run services describe reverse-proxy-backend \
          --region=${_REGION} \
          --format='value(status.url)'
        echo ""
        echo "Frontend (Static - Config ①) URL:"
        gcloud run services describe reverse-proxy-frontend-static \
          --region=${_REGION} \
          --format='value(status.url)'
        echo ""
        echo "Frontend (Proxy - Config ②) URL:"
        gcloud run services describe reverse-proxy-frontend \
          --region=${_REGION} \
          --format='value(status.url)'
        echo "================================================"
    waitFor: ['deploy-frontend-static', 'deploy-frontend']

substitutions:
  _REGION: asia-northeast1
  _REPOSITORY: reverse-proxy

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '3600s'
