# Complete deployment workflow: Build images → Push to Artifact Registry → Deploy with Terraform
steps:
  # Step 1: Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/reverse-proxy-backend:$BUILD_ID'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/reverse-proxy-backend:latest'
      - './backend'
    id: 'build-backend'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'copy-frontend-files'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Removing existing symlinks and copying real files..."
        
        # 1. 既存のシンボリックリンクを削除 (pubspec.*, lib, test, web)
        rm -rf ./frontend-proxy/pubspec.yaml \
                ./frontend-proxy/pubspec.lock \
                ./frontend-proxy/lib \
                ./frontend-proxy/test \
                ./frontend-proxy/web \
                ./frontend-static/pubspec.yaml \
                ./frontend-static/pubspec.lock \
                ./frontend-static/lib \
                ./frontend-static/test \
                ./frontend-static/web
        
        # 2. 実ファイルをコピー
        # frontend-proxy
        cp ./frontend-common/pubspec.yaml ./frontend-proxy/
        cp ./frontend-common/pubspec.lock ./frontend-proxy/
        cp -r ./frontend-common/lib ./frontend-proxy/
        cp -r ./frontend-common/test ./frontend-proxy/
        cp -r ./frontend-common/web ./frontend-proxy/
        
        # frontend-static
        cp ./frontend-common/pubspec.yaml ./frontend-static/
        cp ./frontend-common/pubspec.lock ./frontend-static/
        cp -r ./frontend-common/lib ./frontend-static/
        cp -r ./frontend-common/test ./frontend-static/
        cp -r ./frontend-common/web ./frontend-static/

        echo "Files copied successfully. Checking contents (should not show lrwxrwxrwx):"
        ls -l ./frontend-proxy/
        ls -l ./frontend-static/

  # Step 2: Build frontend-proxy image (reverse proxy)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/reverse-proxy-frontend:$BUILD_ID'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/reverse-proxy-frontend:latest'
      - './frontend-proxy'
    id: 'build-frontend-proxy'
    timeout: '1200s'

  # Step 2.5: Build frontend-static image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/reverse-proxy-frontend-static:$BUILD_ID'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/reverse-proxy-frontend-static:latest'
      - './frontend-static'
    id: 'build-frontend-static'
    timeout: '1200s'

  # Step 3: Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/reverse-proxy-backend'
    id: 'push-backend'
    waitFor: ['build-backend']

  # Step 4: Push frontend-proxy image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/reverse-proxy-frontend'
    id: 'push-frontend-proxy'
    waitFor: ['build-frontend-proxy']

  # Step 4.5: Push frontend-static image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/reverse-proxy-frontend-static'
    id: 'push-frontend-static'
    waitFor: ['build-frontend-static']

  # Step 5: Terraform init with GCS backend
  - name: 'hashicorp/terraform:1.6'
    args:
      - 'init'
      - '-backend-config=bucket=${PROJECT_ID}-terraform-state'
      - '-backend-config=prefix=reverse-proxy'
    dir: 'terraform'
    id: 'terraform-init'
    waitFor: ['push-backend', 'push-frontend-proxy', 'push-frontend-static']

  # Step 6: Terraform plan
  - name: 'hashicorp/terraform:1.6'
    args:
      - 'plan'
      - '-var=project_id=${PROJECT_ID}'
      - '-var=region=${_REGION}'
      - '-var=repository_name=${_REPOSITORY}'
      - '-var=image_tag=$BUILD_ID'
      - '-out=tfplan'
    dir: 'terraform'
    id: 'terraform-plan'
    waitFor: ['terraform-init']

  # Step 7: Terraform apply
  - name: 'hashicorp/terraform:1.6'
    args:
      - 'apply'
      - '-auto-approve'
      - 'tfplan'
    dir: 'terraform'
    id: 'terraform-apply'
    waitFor: ['terraform-plan']

  # Step 8: Get deployment URLs
  - name: 'hashicorp/terraform:1.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "================================================"
        echo "Deployment completed!"
        echo "================================================"
        echo "Backend URL (internal only):"
        terraform output -raw backend_url
        echo ""
        echo "Frontend (Reverse Proxy - Config ②) URL:"
        terraform output -raw frontend_url
        echo ""
        echo "Frontend Static (Config ①) URL:"
        terraform output -raw frontend_static_url
        echo "================================================"
    dir: 'terraform'
    id: 'output-urls'
    waitFor: ['terraform-apply']

substitutions:
  _REGION: asia-northeast1
  _REPOSITORY: reverse-proxy

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '3600s'
