# Complete deployment workflow: Build images → Push to Artifact Registry → Deploy with Terraform
steps:
  # Step 1: Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/reverse-proxy-backend:$BUILD_ID'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/reverse-proxy-backend:latest'
      - './backend'
    id: 'build-backend'

  # Step 2: Build frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/reverse-proxy-frontend:$BUILD_ID'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/reverse-proxy-frontend:latest'
      - './frontend'
    id: 'build-frontend'
    timeout: '1200s'

  # Step 3: Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/reverse-proxy-backend'
    id: 'push-backend'
    waitFor: ['build-backend']

  # Step 4: Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/reverse-proxy-frontend'
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Step 5: Terraform init
  - name: 'hashicorp/terraform:1.6'
    args:
      - 'init'
    dir: 'terraform'
    id: 'terraform-init'
    waitFor: ['push-backend', 'push-frontend']

  # Step 5.5: Import existing Artifact Registry (ignore errors if already imported)
  - name: 'hashicorp/terraform:1.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform import \
          google_artifact_registry_repository.docker_repo \
          projects/${PROJECT_ID}/locations/${_REGION}/repositories/${_REPOSITORY} \
          || echo "Repository already imported or does not exist, continuing..."
    dir: 'terraform'
    id: 'terraform-import'
    waitFor: ['terraform-init']

  # Step 6: Terraform plan
  - name: 'hashicorp/terraform:1.6'
    args:
      - 'plan'
      - '-var=project_id=${PROJECT_ID}'
      - '-var=region=${_REGION}'
      - '-var=repository_name=${_REPOSITORY}'
      - '-var=image_tag=$BUILD_ID'
      - '-out=tfplan'
    dir: 'terraform'
    id: 'terraform-plan'
    waitFor: ['terraform-import']

  # Step 7: Terraform apply
  - name: 'hashicorp/terraform:1.6'
    args:
      - 'apply'
      - '-auto-approve'
      - 'tfplan'
    dir: 'terraform'
    id: 'terraform-apply'
    waitFor: ['terraform-plan']

  # Step 8: Set IAM policies (allow unauthenticated access)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "Setting IAM policies for Cloud Run services..."

        # Allow unauthenticated access to backend (internal only, but needs permission)
        gcloud run services add-iam-policy-binding reverse-proxy-backend \
          --region=${_REGION} \
          --member="allUsers" \
          --role="roles/run.invoker" \
          --quiet || echo "Backend IAM policy already set"

        # Allow unauthenticated access to frontend
        gcloud run services add-iam-policy-binding reverse-proxy-frontend \
          --region=${_REGION} \
          --member="allUsers" \
          --role="roles/run.invoker" \
          --quiet || echo "Frontend IAM policy already set"

        echo "IAM policies set successfully"
    id: 'set-iam-policies'
    waitFor: ['terraform-apply']

  # Step 9: Get deployment URLs
  - name: 'hashicorp/terraform:1.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "================================================"
        echo "Deployment completed!"
        echo "================================================"
        echo "Backend URL (internal only):"
        terraform output -raw backend_url
        echo ""
        echo "Frontend URL (public):"
        terraform output -raw frontend_url
        echo "================================================"
    dir: 'terraform'
    id: 'output-urls'
    waitFor: ['set-iam-policies']

substitutions:
  _REGION: asia-northeast1
  _REPOSITORY: reverse-proxy

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '3600s'
